from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # LLM backend — Groq hosts open-weight models (Qwen, GPT-OSS) for free.
    # SEMBLANCE never claims to be Claude or any other vendor's model.
    #
    # Both of these were confirmed against this account's actual
    # `GET /openai/v1/models` list, not just Groq's public docs — a model
    # can be publicly documented and still 404 as "does not exist or you do
    # not have access to it" if it's not enabled for this specific
    # account/tier. That's what happened with qwen/qwen3-32b and
    # deepseek-r1-distill-llama-70b, both real, documented Groq models that
    # simply aren't in this account's catalog. Re-check with the same query
    # before changing either value:
    #   curl https://api.groq.com/openai/v1/models -H "Authorization: Bearer $GROQ_API_KEY"
    GROQ_API_KEY: str = ""
    GROQ_MODEL: str = "qwen/qwen3.8-27b"          # primary conversational model
    GROQ_PLANNING_MODEL: str = "openai/gpt-oss-120b"  # ULTRAPLAN deep reasoning
    # Neither model above accepts image input — when a message has an image
    # attached, Bootstrap switches to this one instead. Same "re-verify
    # against this account's actual model list" caveat as above.
    GROQ_VISION_MODEL: str = "meta-llama/llama-4-scout-17b-16e-instruct"

    # Optional fallback for when Groq itself is rate-limited (a daily/
    # hourly quota, not the per-minute window QueryEngine already retries
    # through) — Cohere's free "Trial" key is rate-limited and explicitly
    # not for production use per Cohere's own terms, but it's exactly
    # enough to answer the occasional message that would otherwise just
    # get "try again in ~11 minutes." Left blank, this is a no-op and
    # stream_llm behaves exactly as it did before (see RateLimitError).
    COHERE_API_KEY: str = ""
    COHERE_MODEL: str = "command-a-03-2025"

    # Self-hosted overflow brain — Ternary Bonsai 2 27B on Modal
    # (modal_app/llm.py), tried before Cohere once Groq's quota isn't worth
    # retrying through. Same Qwen3.8-27B base as GROQ_MODEL, no per-minute
    # token cap, so replies from it get a much larger budget. Scales to zero:
    # the first call after it's been idle waits ~1 minute for the GPU to wake.
    # Left blank, this is a no-op.
    LOCAL_LLM_URL: str = ""
    LOCAL_LLM_API_KEY: str = ""
    LOCAL_LLM_MODEL: str = "bonsai-2-27b"
    LOCAL_LLM_MAX_TOKENS: int = 4096

    # Model picker (pipeline/llm_providers.py). Free options first; each
    # provider shows up in the picker only once its key is set. Model IDs
    # are settings so a newer release is a config change, not a code change.
    # Google AI Studio key — Gemini's free tier (Flash models), plus Nano
    # Banana images and Gemini TTS for the Design tab.
    GEMINI_API_KEY: str = ""
    GEMINI_MODEL: str = "gemini-flash-latest"
    GEMINI_IMAGE_MODEL: str = "gemini-2.5-flash-image"
    GEMINI_TTS_MODEL: str = "gemini-2.5-flash-preview-tts"
    # Paid options.
    ANTHROPIC_API_KEY: str = ""
    ANTHROPIC_MODEL: str = "claude-opus-5-5"
    OPENAI_API_KEY: str = ""
    OPENAI_MODEL: str = "gpt-6.1-sol"
    # Alibaba Cloud Model Studio (DashScope), international endpoint.
    QWEN_API_KEY: str = ""
    QWEN_MODEL: str = "qwen-max"
    QWEN_BASE_URL: str = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
    DEEPSEEK_API_KEY: str = ""
    DEEPSEEK_MODEL: str = "deepseek-chat"
    KIMI_API_KEY: str = ""
    KIMI_MODEL: str = "kimi-latest"
    # Hugging Face Inference Providers router: any chat model HF serves,
    # picked by its repo id ("hf:owner/model" in the picker). A free HF
    # account gets a small monthly credit; beyond that it's pay-as-you-go.
    HF_TOKEN: str = ""
    HF_MODEL: str = "openai/gpt-oss-120b"

    # Storage — Neon serverless Postgres (+ pgvector) replaces Aiven MySQL + ChromaDB.
    # One database, two roles: raw records and vector search over the same rows.
    NEON_DATABASE_URL: str = "postgresql://user:pass@host/semblance?sslmode=require"

    # Embeddings — generated by a Modal function (sentence-transformers), called over HTTP.
    # Keeps the Lambda package small and avoids loading an ML model on every cold start.
    MODAL_EMBEDDINGS_URL: str = ""
    # Emotion classifier on the same Modal app; derived from the embeddings
    # URL ("-embed." -> "-emotion.") when left blank.
    MODAL_EMOTION_URL: str = ""

    # Persistent repo clone/read/grep — a separate Modal function
    # (modal_app/repo_tool.py) that keeps a git clone on a Modal Volume
    # between calls, so re-asking about the same repo doesn't re-fetch it
    # from scratch. Unlike MODAL_EMBEDDINGS_URL, this endpoint can clone
    # private repos and read arbitrary files, so it's also secret-gated.
    MODAL_REPO_URL: str = ""
    MODAL_REPO_SECRET: str = ""

    # Video ads (modal_app/video.py): Wan 2.1 on Modal with its own monthly
    # spend cap, set in the Modal secret (VIDEO_MONTHLY_CAP_USD).
    MODAL_VIDEO_URL: str = ""
    MODAL_VIDEO_SECRET: str = ""
    MODAL_FREE_CREDIT_USD: float = 30.0  # Modal Starter plan's free compute each month

    # Cache — DynamoDB-backed, in-memory L1 on top for warm Lambda invocations.
    CACHE_TABLE_NAME: str = "semblance-cache"
    AWS_REGION: str = "us-east-1"

    # Optional tools
    # Self-hosted SearXNG (modal_app/searxng.py): open-source metasearch, no
    # quota. Used first when set; SerpAPI (100 searches/month free) otherwise.
    SEARXNG_URL: str = ""
    SERP_API_KEY: str = ""
    WHATSAPP_TOKEN: str = ""
    WHATSAPP_PHONE_ID: str = ""
    GITHUB_WEBHOOK_SECRET: str = ""  # the repo webhook's secret; /webhook/github checks signatures when set
    WHATSAPP_VERIFY_TOKEN: str = ""  # arbitrary string you also enter in the Meta App Dashboard webhook config
    OPENCLAW_URL: str = ""  # optional self-hosted WhatsApp/Telegram/Slack bridge
    # KAIROS (agents/kairos.py, every EventBridge tick): delivers due
    # reminders and a once-a-day morning brief (calendar + unread email +
    # today's reminders). Both always land in the app as a chat; set
    # OWNER_WHATSAPP_NUMBER (international format, no +) to also get them
    # on WhatsApp via the Cloud API credentials above.
    OWNER_ACCOUNT_ID: str = "owner"
    # Approved AWS changes stop (deletes/stops excepted) once the month's bill reaches this.
    AWS_SPEND_LIMIT_USD: float = 5.0
    OWNER_WHATSAPP_NUMBER: str = ""
    KAIROS_MORNING_BRIEF: bool = True
    KAIROS_BRIEF_HOUR: int = 7  # South Africa time
    # Optional: JSON object of name -> base_url, e.g.
    # {"slack": "https://my-slack-mcp.example.com"} — each gets registered
    # with the shared MCPTool instance (tools/mcp_tool.py) at startup, so
    # the "mcp" tool in the registry actually has a server to call. Left
    # unset, "mcp" stays registered but every call returns a clear "not
    # registered" error, same as any other unconfigured optional tool here.
    MCP_SERVERS: str = ""

    # Agent limits (Code, Co-work, Research, scheduled automations). The chat
    # Lambda's own ceiling is 900s (template.yaml), so keep timeouts under it.
    CODE_MAX_STEPS: int = 30
    COWORK_MAX_STEPS: int = 25
    RESEARCH_MAX_STEPS: int = 16
    AGENT_TIMEOUT_SECONDS: int = 780
    RESEARCH_TIMEOUT_SECONDS: int = 600
    AUTOMATION_MAX_STEPS: int = 20
    AUTOMATION_TIMEOUT_SECONDS: int = 600

    SECRET_KEY: str = "change-me"
    TRUST_MODE: str = "AUTO"  # BYPASS | ALLOW_EDITS | AUTO

    # OAuth for the GitHub/GitLab connectors — lets "Connect GitHub" redirect
    # to GitHub's own consent screen instead of asking for a pasted PAT.
    # Each requires a one-time OAuth App registered by the account owner
    # (github.com/settings/developers, gitlab.com/-/user_settings/applications)
    # with its callback URL set to {PUBLIC_API_URL}/connectors/<provider>/callback.
    # Left blank, /connectors/{provider}/authorize returns a clear error and
    # the manual-token flow still works as a fallback.
    GITHUB_CLIENT_ID: str = ""
    GITHUB_CLIENT_SECRET: str = ""
    GITLAB_CLIENT_ID: str = ""
    GITLAB_CLIENT_SECRET: str = ""
    # OAuth for Calendar/Gmail/Drive/Contacts — one consent screen covers all
    # four (see gateway/google_oauth.py's SCOPES). One-time OAuth client
    # registered by the account owner at console.cloud.google.com
    # (APIs & Services > Credentials > Create OAuth client ID > Web
    # application), with Calendar/Gmail/Drive/People APIs enabled for the
    # project and this exact redirect URI added:
    # {PUBLIC_API_URL}/connectors/google/callback
    GOOGLE_CLIENT_ID: str = ""
    GOOGLE_CLIENT_SECRET: str = ""
    # The Lambda Function URL itself — used to build the exact OAuth redirect_uri,
    # which must match what's registered in the OAuth App byte-for-byte. Not
    # inferred from the incoming request's Host header, to avoid depending on
    # proxy headers surviving the Lambda Web Adapter hop uncorrupted.
    PUBLIC_API_URL: str = ""

    model_config = SettingsConfigDict(env_file=".env")


settings = Settings()
